In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Food_Delivery_Sales.csv")

In [3]:
print(df)

    Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
0       1001  01-09-2026    Rahul    Delhi    North Indian    Delivered
1       1002  01-09-2026    Priya     Agra         Chinese    Delivered
2       1003  02-09-2026     Aman   Jaipur       Fast Food    Cancelled
3       1004  02-09-2026     Neha    Delhi    South Indian    Delivered
4       1005  03-09-2026    Rohit  Lucknow    North Indian    Delivered
5       1006  03-09-2026   Simran     Agra       Fast Food      Pending
6       1007  04-09-2026    Karan   Jaipur         Chinese    Delivered
7       1008  04-09-2026   Anjali    Delhi       Fast Food    Delivered
8       1009  05-09-2026    Vivek  Lucknow    South Indian    Cancelled
9       1010  05-09-2026    Pooja     Agra    North Indian    Delivered
10      1011  06-09-2026    Arjun    Delhi         Chinese    Delivered
11      1012  06-09-2026     Riya   Jaipur       Fast Food    Delivered

    Quantity  Order_Value Payment_Mode
0          2          450          UPI
1          3          620         Card
2          1          250          UPI
3          2          380         Cash
4          4          850          UPI
5          2          340         Card
6          3          720          UPI
7          1          210         Cash
8          2          400          UPI
9          3          690         Card
10         2          560          UPI
11         4          780         Cash

In [4]:
print(df.head())

   Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
0      1001  01-09-2026    Rahul    Delhi    North Indian    Delivered
1      1002  01-09-2026    Priya     Agra         Chinese    Delivered
2      1003  02-09-2026     Aman   Jaipur       Fast Food    Cancelled
3      1004  02-09-2026     Neha    Delhi    South Indian    Delivered
4      1005  03-09-2026    Rohit  Lucknow    North Indian    Delivered

   Quantity  Order_Value Payment_Mode
0         2          450          UPI
1         3          620         Card
2         1          250          UPI
3         2          380         Cash
4         4          850          UPI

In [5]:
print(df.tail())

    Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
7       1008  04-09-2026   Anjali    Delhi       Fast Food    Delivered
8       1009  05-09-2026    Vivek  Lucknow    South Indian    Cancelled
9       1010  05-09-2026    Pooja     Agra    North Indian    Delivered
10      1011  06-09-2026    Arjun    Delhi         Chinese    Delivered
11      1012  06-09-2026     Riya   Jaipur       Fast Food    Delivered

    Quantity  Order_Value Payment_Mode
7          1          210         Cash
8          2          400          UPI
9          3          690         Card
10         2          560          UPI
11         4          780         Cash

In [6]:
print(df.shape)

(12, 9)

In [7]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Restaurant_Type',
       'Order_Status', 'Quantity', 'Order_Value', 'Payment_Mode'],
      dtype='str')

In [8]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         12 non-null     int64
 1   Order_Date       12 non-null     str
 2   Customer         12 non-null     str
 3   City             12 non-null     str
 4   Restaurant_Type  12 non-null     str
 5   Order_Status     12 non-null     str
 6   Quantity         12 non-null     int64
 7   Order_Value      12 non-null     int64
 8   Payment_Mode     12 non-null     str
dtypes: int64(3), str(6)
memory usage: 996.0 bytes
None

In [9]:
print(df.dtypes)

Order_ID           int64
Order_Date           str
Customer             str
City                 str
Restaurant_Type      str
Order_Status         str
Quantity           int64
Order_Value        int64
Payment_Mode         str
dtype: object

In [10]:
print(df.isnull().sum())

Order_ID           0
Order_Date         0
Customer           0
City               0
Restaurant_Type    0
Order_Status       0
Quantity           0
Order_Value        0
Payment_Mode       0
dtype: int64

In [11]:
print(df.duplicated().sum())

0

In [12]:
print(df.describe())

          Order_ID   Quantity  Order_Value
count    12.000000  12.000000    12.000000
mean   1006.500000   2.416667   520.833333
std       3.605551   0.996205   212.622514
min    1001.000000   1.000000   210.000000
25%    1003.750000   2.000000   370.000000
50%    1006.500000   2.000000   505.000000
75%    1009.250000   3.000000   697.500000
max    1012.000000   4.000000   850.000000

In [13]:
print(df.nunique())

Order_ID           12
Order_Date          6
Customer           12
City                4
Restaurant_Type     4
Order_Status        3
Quantity            4
Order_Value        12
Payment_Mode        3
dtype: int64

In [15]:
print(df["City"].unique())

<StringArray>
['Delhi', 'Agra', 'Jaipur', 'Lucknow']
Length: 4, dtype: str

In [16]:
print(df["Restaurant_Type"].unique())

<StringArray>
['North Indian', 'Chinese', 'Fast Food', 'South Indian']
Length: 4, dtype: str

In [17]:
print(df["Order_Status"].unique())

<StringArray>
['Delivered', 'Cancelled', 'Pending']
Length: 3, dtype: str

In [18]:
print(df["Payment_Mode"].unique())

<StringArray>
['UPI', 'Card', 'Cash']
Length: 3, dtype: str

In [19]:
df.columns = df.columns.str.strip()

In [20]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Restaurant_Type',
       'Order_Status', 'Quantity', 'Order_Value', 'Payment_Mode'],
      dtype='str')

In [21]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [22]:
print(df.dtypes)

Order_ID                    int64
Order_Date         datetime64[us]
Customer                      str
City                          str
Restaurant_Type               str
Order_Status                  str
Quantity                    int64
Order_Value                 int64
Payment_Mode                  str
dtype: object

In [23]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         12 non-null     int64
 1   Order_Date       12 non-null     datetime64[us]
 2   Customer         12 non-null     str
 3   City             12 non-null     str
 4   Restaurant_Type  12 non-null     str
 5   Order_Status     12 non-null     str
 6   Quantity         12 non-null     int64
 7   Order_Value      12 non-null     int64
 8   Payment_Mode     12 non-null     str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 996.0 bytes
None

In [24]:
# Analysis

In [25]:
df[df["Order_Status"] == "Delivered"]

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode
0,1001,2026-01-09,Rahul,Delhi,North Indian,Delivered,2,450,UPI
1,1002,2026-01-09,Priya,Agra,Chinese,Delivered,3,620,Card
3,1004,2026-02-09,Neha,Delhi,South Indian,Delivered,2,380,Cash
4,1005,2026-03-09,Rohit,Lucknow,North Indian,Delivered,4,850,UPI
6,1007,2026-04-09,Karan,Jaipur,Chinese,Delivered,3,720,UPI
7,1008,2026-04-09,Anjali,Delhi,Fast Food,Delivered,1,210,Cash
9,1010,2026-05-09,Pooja,Agra,North Indian,Delivered,3,690,Card
10,1011,2026-06-09,Arjun,Delhi,Chinese,Delivered,2,560,UPI
11,1012,2026-06-09,Riya,Jaipur,Fast Food,Delivered,4,780,Cash

In [26]:
df[df["Order_Status"] == "Cancelled"]

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode
2,1003,2026-02-09,Aman,Jaipur,Fast Food,Cancelled,1,250,UPI
8,1009,2026-05-09,Vivek,Lucknow,South Indian,Cancelled,2,400,UPI

In [27]:
df[df["Order_Status"] == "Pending"]

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode
5,1006,2026-03-09,Simran,Agra,Fast Food,Pending,2,340,Card

In [28]:
df["City"].value_counts()

City
Delhi      4
Agra       3
Jaipur     3
Lucknow    2
Name: count, dtype: int64

In [29]:
df["Restaurant_Type"].value_counts()

Restaurant_Type
Fast Food       4
North Indian    3
Chinese         3
South Indian    2
Name: count, dtype: int64

In [30]:
df["Payment_Mode"].value_counts()

Payment_Mode
UPI     6
Card    3
Cash    3
Name: count, dtype: int64

In [31]:
df["Order_Value"].sum()

np.int64(6250)

In [32]:
df["Order_Value"].mean()

np.float64(520.8333333333334)

In [34]:
df["Order_Value"].max()

np.int64(850)

In [35]:
df["Order_Value"].min()

np.int64(210)

In [36]:
df.groupby("City")["Order_Value"].sum()

City
Agra       1650
Delhi      1600
Jaipur     1750
Lucknow    1250
Name: Order_Value, dtype: int64

In [37]:
df.groupby("Restaurant_Type")["Order_Value"].sum()

Restaurant_Type
Chinese         1900
Fast Food       1580
North Indian    1990
South Indian     780
Name: Order_Value, dtype: int64

In [38]:
df.groupby("Payment_Mode")["Order_Value"].sum()

Payment_Mode
Card    1650
Cash    1370
UPI     3230
Name: Order_Value, dtype: int64

In [39]:
df.groupby("Order_Status")["Order_Value"].sum()

Order_Status
Cancelled     650
Delivered    5260
Pending       340
Name: Order_Value, dtype: int64

In [40]:
df.groupby(["City","Restaurant_Type"])["Order_Value"].sum()

City     Restaurant_Type
Agra     Chinese             620
         Fast Food           340
         North Indian        690
Delhi    Chinese             560
         Fast Food           210
         North Indian        450
         South Indian        380
Jaipur   Chinese             720
         Fast Food          1030
Lucknow  North Indian        850
         South Indian        400
Name: Order_Value, dtype: int64

In [41]:
df["Quantity"].sum()

np.int64(29)

In [42]:
df["Quantity"].mean()

np.float64(2.4166666666666665)

In [43]:
df.groupby("Restaurant_Type")["Quantity"].sum()

Restaurant_Type
Chinese         8
Fast Food       8
North Indian    9
South Indian    4
Name: Quantity, dtype: int64

In [44]:
df["Price_Per_Item"] = df["Order_Value"]/df["Quantity"]

In [46]:
print(df.head())

   Order_ID Order_Date Customer     City Restaurant_Type Order_Status  \
0      1001 2026-01-09    Rahul    Delhi    North Indian    Delivered
1      1002 2026-01-09    Priya     Agra         Chinese    Delivered
2      1003 2026-02-09     Aman   Jaipur       Fast Food    Cancelled
3      1004 2026-02-09     Neha    Delhi    South Indian    Delivered
4      1005 2026-03-09    Rohit  Lucknow    North Indian    Delivered

   Quantity  Order_Value Payment_Mode  Price_Per_Item
0         2          450          UPI      225.000000
1         3          620         Card      206.666667
2         1          250          UPI      250.000000
3         2          380         Cash      190.000000
4         4          850          UPI      212.500000

In [47]:
df[df["Order_Value"]>500]

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode,Price_Per_Item
1,1002,2026-01-09,Priya,Agra,Chinese,Delivered,3,620,Card,206.666667
4,1005,2026-03-09,Rohit,Lucknow,North Indian,Delivered,4,850,UPI,212.500000
6,1007,2026-04-09,Karan,Jaipur,Chinese,Delivered,3,720,UPI,240.000000
9,1010,2026-05-09,Pooja,Agra,North Indian,Delivered,3,690,Card,230.000000
10,1011,2026-06-09,Arjun,Delhi,Chinese,Delivered,2,560,UPI,280.000000
11,1012,2026-06-09,Riya,Jaipur,Fast Food,Delivered,4,780,Cash,195.000000

In [50]:
df.sort_values("Order_Value",ascending = False)

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode,Price_Per_Item
4,1005,2026-03-09,Rohit,Lucknow,North Indian,Delivered,4,850,UPI,212.500000
11,1012,2026-06-09,Riya,Jaipur,Fast Food,Delivered,4,780,Cash,195.000000
6,1007,2026-04-09,Karan,Jaipur,Chinese,Delivered,3,720,UPI,240.000000
9,1010,2026-05-09,Pooja,Agra,North Indian,Delivered,3,690,Card,230.000000
1,1002,2026-01-09,Priya,Agra,Chinese,Delivered,3,620,Card,206.666667
10,1011,2026-06-09,Arjun,Delhi,Chinese,Delivered,2,560,UPI,280.000000
0,1001,2026-01-09,Rahul,Delhi,North Indian,Delivered,2,450,UPI,225.000000
8,1009,2026-05-09,Vivek,Lucknow,South Indian,Cancelled,2,400,UPI,200.000000
3,1004,2026-02-09,Neha,Delhi,South Indian,Delivered,2,380,Cash,190.000000
5,1006,2026-03-09,Simran,Agra,Fast Food,Pending,2,340,Card,170.000000
2,1003,2026-02-09,Aman,Jaipur,Fast Food,Cancelled,1,250,UPI,250.000000
7,1008,2026-04-09,Anjali,Delhi,Fast Food,Delivered,1,210,Cash,210.000000

In [51]:
df.sort_values("Quantity",ascending = False)

,Order_ID,Order_Date,Customer,City,Restaurant_Type,Order_Status,Quantity,Order_Value,Payment_Mode,Price_Per_Item
11,1012,2026-06-09,Riya,Jaipur,Fast Food,Delivered,4,780,Cash,195.000000
4,1005,2026-03-09,Rohit,Lucknow,North Indian,Delivered,4,850,UPI,212.500000
1,1002,2026-01-09,Priya,Agra,Chinese,Delivered,3,620,Card,206.666667
9,1010,2026-05-09,Pooja,Agra,North Indian,Delivered,3,690,Card,230.000000
6,1007,2026-04-09,Karan,Jaipur,Chinese,Delivered,3,720,UPI,240.000000
8,1009,2026-05-09,Vivek,Lucknow,South Indian,Cancelled,2,400,UPI,200.000000
0,1001,2026-01-09,Rahul,Delhi,North Indian,Delivered,2,450,UPI,225.000000
3,1004,2026-02-09,Neha,Delhi,South Indian,Delivered,2,380,Cash,190.000000
10,1011,2026-06-09,Arjun,Delhi,Chinese,Delivered,2,560,UPI,280.000000
5,1006,2026-03-09,Simran,Agra,Fast Food,Pending,2,340,Card,170.000000
2,1003,2026-02-09,Aman,Jaipur,Fast Food,Cancelled,1,250,UPI,250.000000
7,1008,2026-04-09,Anjali,Delhi,Fast Food,Delivered,1,210,Cash,210.000000

In [52]:
print(df.isnull().sum())

Order_ID           0
Order_Date         0
Customer           0
City               0
Restaurant_Type    0
Order_Status       0
Quantity           0
Order_Value        0
Payment_Mode       0
Price_Per_Item     0
dtype: int64

In [53]:
print(df.duplicated().sum())

0

In [54]:
print(df)

    Order_ID Order_Date Customer     City Restaurant_Type Order_Status  \
0       1001 2026-01-09    Rahul    Delhi    North Indian    Delivered
1       1002 2026-01-09    Priya     Agra         Chinese    Delivered
2       1003 2026-02-09     Aman   Jaipur       Fast Food    Cancelled
3       1004 2026-02-09     Neha    Delhi    South Indian    Delivered
4       1005 2026-03-09    Rohit  Lucknow    North Indian    Delivered
5       1006 2026-03-09   Simran     Agra       Fast Food      Pending
6       1007 2026-04-09    Karan   Jaipur         Chinese    Delivered
7       1008 2026-04-09   Anjali    Delhi       Fast Food    Delivered
8       1009 2026-05-09    Vivek  Lucknow    South Indian    Cancelled
9       1010 2026-05-09    Pooja     Agra    North Indian    Delivered
10      1011 2026-06-09    Arjun    Delhi         Chinese    Delivered
11      1012 2026-06-09     Riya   Jaipur       Fast Food    Delivered

    Quantity  Order_Value Payment_Mode  Price_Per_Item
0          2          450          UPI      225.000000
1          3          620         Card      206.666667
2          1          250          UPI      250.000000
3          2          380         Cash      190.000000
4          4          850          UPI      212.500000
5          2          340         Card      170.000000
6          3          720          UPI      240.000000
7          1          210         Cash      210.000000
8          2          400          UPI      200.000000
9          3          690         Card      230.000000
10         2          560          UPI      280.000000
11         4          780         Cash      195.000000

In [55]:
df.to_csv("Food_Delivery_Sales_Cleaned.csv",index = False)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Food_Delivery_Sales_cleaned.csv")

In [4]:
print(df.head())

   Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
0      1001  2026-01-09    Rahul    Delhi    North Indian    Delivered
1      1002  2026-01-09    Priya     Agra         Chinese    Delivered
2      1003  2026-02-09     Aman   Jaipur       Fast Food    Cancelled
3      1004  2026-02-09     Neha    Delhi    South Indian    Delivered
4      1005  2026-03-09    Rohit  Lucknow    North Indian    Delivered

   Quantity  Order_Value Payment_Mode  Price_Per_Item
0         2          450          UPI      225.000000
1         3          620         Card      206.666667
2         1          250          UPI      250.000000
3         2          380         Cash      190.000000
4         4          850          UPI      212.500000

In [8]:
df["Sales %"] = (df["Order_Value"]/df["Order_Value"].sum())*100

In [9]:
df[["Order_ID","Order_Value","Sales %"]]

    Order_ID  Order_Value  Sales %
0       1001          450     7.20
1       1002          620     9.92
2       1003          250     4.00
3       1004          380     6.08
4       1005          850    13.60
5       1006          340     5.44
6       1007          720    11.52
7       1008          210     3.36
8       1009          400     6.40
9       1010          690    11.04
10      1011          560     8.96
11      1012          780    12.48

In [10]:
df["Sales %"].sum()

np.float64(100.0)

In [11]:
df.to_csv("Food_Delivery_Sales_Final.csv",index = False)

In [12]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Restaurant_Type',
       'Order_Status', 'Quantity', 'Order_Value', 'Payment_Mode',
       'Price_Per_Item', 'Sales %'],
      dtype='str')

In [2]:
import pandas as pd
df = pd.read_csv("Food_Delivery_Sales_Final.csv")
print(df.head())

   Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
0      1001  2026-01-09    Rahul    Delhi    North Indian    Delivered
1      1002  2026-01-09    Priya     Agra         Chinese    Delivered
2      1003  2026-02-09     Aman   Jaipur       Fast Food    Cancelled
3      1004  2026-02-09     Neha    Delhi    South Indian    Delivered
4      1005  2026-03-09    Rohit  Lucknow    North Indian    Delivered

   Quantity  Order_Value Payment_Mode  Price_Per_Item  Sales %
0         2          450          UPI      225.000000     7.20
1         3          620         Card      206.666667     9.92
2         1          250          UPI      250.000000     4.00
3         2          380         Cash      190.000000     6.08
4         4          850          UPI      212.500000    13.60

In [4]:
df["Total Sales"] = df["Quantity"]*df["Price_Per_Item"]
print(df)

    Order_ID  Order_Date Customer     City Restaurant_Type Order_Status  \
0       1001  2026-01-09    Rahul    Delhi    North Indian    Delivered
1       1002  2026-01-09    Priya     Agra         Chinese    Delivered
2       1003  2026-02-09     Aman   Jaipur       Fast Food    Cancelled
3       1004  2026-02-09     Neha    Delhi    South Indian    Delivered
4       1005  2026-03-09    Rohit  Lucknow    North Indian    Delivered
5       1006  2026-03-09   Simran     Agra       Fast Food      Pending
6       1007  2026-04-09    Karan   Jaipur         Chinese    Delivered
7       1008  2026-04-09   Anjali    Delhi       Fast Food    Delivered
8       1009  2026-05-09    Vivek  Lucknow    South Indian    Cancelled
9       1010  2026-05-09    Pooja     Agra    North Indian    Delivered
10      1011  2026-06-09    Arjun    Delhi         Chinese    Delivered
11      1012  2026-06-09     Riya   Jaipur       Fast Food    Delivered

    Quantity  Order_Value Payment_Mode  Price_Per_Item  Sales %  Total Sales
0          2          450          UPI      225.000000     7.20        450.0
1          3          620         Card      206.666667     9.92        620.0
2          1          250          UPI      250.000000     4.00        250.0
3          2          380         Cash      190.000000     6.08        380.0
4          4          850          UPI      212.500000    13.60        850.0
5          2          340         Card      170.000000     5.44        340.0
6          3          720          UPI      240.000000    11.52        720.0
7          1          210         Cash      210.000000     3.36        210.0
8          2          400          UPI      200.000000     6.40        400.0
9          3          690         Card      230.000000    11.04        690.0
10         2          560          UPI      280.000000     8.96        560.0
11         4          780         Cash      195.000000    12.48        780.0

In [5]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         12 non-null     int64
 1   Order_Date       12 non-null     str
 2   Customer         12 non-null     str
 3   City             12 non-null     str
 4   Restaurant_Type  12 non-null     str
 5   Order_Status     12 non-null     str
 6   Quantity         12 non-null     int64
 7   Order_Value      12 non-null     int64
 8   Payment_Mode     12 non-null     str
 9   Price_Per_Item   12 non-null     float64
 10  Sales %          12 non-null     float64
 11  Total Sales      12 non-null     float64
dtypes: float64(3), int64(3), str(6)
memory usage: 1.3 KB
None